services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: B-Tak_Toek-db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    container_name: idcard-web
    depends_on:
      - mysql
    ports:
      - "8443:8080"
      - "2222:22"
    volumes:
      - gradle-cache:/root/.gradle

volumes:
  mysql-data:
  gradle-cache:
